name: Build and Deploy Blog

on:
  push:
    branches:
      - main  # Ana branşa push yapıldığında tetiklenecek
  pull_request:
    branches:
      - main  # Ana branşta pull request oluşturulduğunda tetiklenecek

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu üzerinde çalışacak

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Reponun içeriğini çeker

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Python 3.12 kullanılıyor

      - name: Install Dependencies
        run: |
          pip install markdown  # Markdown modülünü yükle

      - name: Eski dosyaları sil
        run: |
          rm pages-html/*

      - name: Generate Blog Pages
        run: |
          python generator.py  # Python scriptini çalıştırarak HTML dosyalarını oluştur

      - name: Copy font
        run: |
          cp WinkyRough-Regular.ttf pages-html/WinkyRough-Regular.ttf

      - name: Check for Changes
        run: |
          git status
          git diff --stat

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token'ı kullanılıyor
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A  # Tüm dosyaları ekle
          git commit -m "Update blog pages" || echo "No changes to commit"
          git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
